from src.domain import Vocabulary, CEFRLevel

DEFAULT_NUMBER_OF_QUESTIONS: int = 8
DEFAULT_NUMBER_OF_SENTENCES: int = 4
SECONDS_PER_QUESTION: int = 40

DEFAULT_VOCABULARY: Vocabulary = Vocabulary.GERMAN
DEFAULT_CEFR_LEVEL: CEFRLevel = CEFRLevel.B2

LATEST_FILES_NUMBER: int = 2

UNSEEN_ALPHA = 30
